# Generated by Django 4.0.4 on 2022-07-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.FilePathField(path='Blog\\blogs'),
        ),
    ]
