# Generated by Django 4.0.8 on 2023-10-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircooler',
            old_name='width',
            new_name='length',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='depth',
            new_name='length',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='base_speed',
            new_name='base_clock',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='boost_speed',
            new_name='boost_clock',
        ),
        migrations.RenameField(
            model_name='gpu',
            old_name='cude_cores',
            new_name='cores',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='monitor_count',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='multimonitor_support',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='stream_processors',
        ),
        migrations.AddField(
            model_name='aircooler',
            name='relativeSize',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='relativeSize',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='cpu',
            name='relativeSize',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='fan',
            name='relativeSize',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='relativeSize',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='hdd',
            name='relativeSize',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='relativeSize',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='psu',
            name='relativeSize',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='ram',
            name='relativeSize',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='ssd',
            name='relativeSize',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='watercooler',
            name='relativeSize',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='height',
            field=models.FloatField(help_text='*in inches', null=True),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='supported_resolution',
            field=models.CharField(choices=[(1000, '1K'), (2000, '2K'), (4000, '4K'), (5000, '5K'), (8000, '8K')], max_length=5, verbose_name='Maximum supported resolutions'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='width',
            field=models.FloatField(help_text='*in inches', null=True),
        ),
    ]
