# Generated by Django 4.0.8 on 2023-10-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parts', '0002_rename_width_aircooler_length_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='max_cpu_cooler_heigth',
            new_name='max_radiator_size',
        ),
        migrations.RemoveField(
            model_name='case',
            name='height',
        ),
        migrations.RemoveField(
            model_name='case',
            name='length',
        ),
        migrations.RemoveField(
            model_name='case',
            name='width',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='argb_headers',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='fan_headers',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='rgb_headers',
        ),
        migrations.AlterField(
            model_name='case',
            name='mobo_support',
            field=models.IntegerField(choices=[('ATX', 'ATX'), ('Micro-ATX', 'Micro-ATX'), ('Mini-ITX', 'MiniI-TX')]),
        ),
    ]
