# Generated by Django 4.0.8 on 2023-10-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parts', '0003_rename_max_cpu_cooler_heigth_case_max_radiator_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircooler',
            name='amazon_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aircooler',
            name='amazon_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aircooler',
            name='newegg_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aircooler',
            name='newegg_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='amazon_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='amazon_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='mobo_support',
            field=models.CharField(choices=[('ATX', 'ATX'), ('Micro-ATX', 'Micro-ATX'), ('Mini-ITX', 'MiniI-TX')], max_length=10),
        ),
        migrations.AlterField(
            model_name='case',
            name='newegg_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='newegg_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='amazon_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='amazon_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='newegg_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='newegg_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fan',
            name='amazon_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fan',
            name='amazon_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fan',
            name='newegg_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fan',
            name='newegg_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='amazon_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='amazon_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='newegg_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='newegg_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='amazon_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='amazon_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='newegg_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='newegg_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='amazon_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='amazon_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='newegg_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='newegg_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psu',
            name='amazon_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psu',
            name='amazon_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psu',
            name='newegg_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psu',
            name='newegg_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psu',
            name='size',
            field=models.CharField(choices=[('ATX', 'ATX'), ('Micro-ATX', 'Micro-ATX'), ('Mini-ITX', 'Mini-ITX')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ram',
            name='amazon_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ram',
            name='amazon_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ram',
            name='newegg_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ram',
            name='newegg_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='amazon_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='amazon_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='newegg_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='newegg_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='watercooler',
            name='amazon_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='watercooler',
            name='amazon_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='watercooler',
            name='newegg_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='watercooler',
            name='newegg_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
