# Generated by Django 4.0.8 on 2023-10-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parts', '0005_remove_ram_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watercooler',
            name='size',
        ),
        migrations.AlterField(
            model_name='aircooler',
            name='socket',
            field=models.CharField(choices=[('AM5', 'AM5'), ('AM4', 'AM4'), ('LGA 1700', 'LGA 1700'), ('LGA 1200', 'LGA 1200'), ('LGA 1151', 'LGA 1151'), ('AMD Intel', 'AMD INTEL')], max_length=15),
        ),
        migrations.AlterField(
            model_name='watercooler',
            name='socket',
            field=models.IntegerField(choices=[('AM5', 'AM5'), ('AM4', 'AM4'), ('LGA 1700', 'LGA 1700'), ('LGA 1200', 'LGA 1200'), ('LGA 1151', 'LGA 1151'), ('AMD and Intel', 'AMD and Intel')]),
        ),
    ]
