# Generated by Django 4.0.8 on 2023-10-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parts', '0007_remove_watercooler_width_alter_watercooler_socket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpu',
            name='has_displayport',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='has_hdmi',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='has_usbc',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='pcie_4_support',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='pcie_5_support',
        ),
        migrations.RemoveField(
            model_name='gpu',
            name='pins_num',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='has_displayport',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='has_hdmi',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='has_usbc',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='pcie_4_support',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='pcie_5_support',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='sata_slots',
        ),
        migrations.RemoveField(
            model_name='motherboard',
            name='usb3point2_support',
        ),
        migrations.AddField(
            model_name='gpu',
            name='pcie_version',
            field=models.BooleanField(null=True, verbose_name='Which PCIe verison (type only 5 or4)'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='pin_num',
            field=models.PositiveIntegerField(help_text='Number of pins to power the card', null=True, verbose_name='Pins required'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='pcie_version',
            field=models.BooleanField(null=True, verbose_name='Which Pcie verison (type only 5 or4)'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='rgb',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='theme',
            field=models.CharField(choices=[('dark', 'dark'), ('light', 'light')], max_length=6),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='usbc_count',
            field=models.PositiveIntegerField(null=True, verbose_name='USB-C ports count'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='integrated_io_sheild',
            field=models.BooleanField(help_text='Does it have a built in cover on io'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='ram_slots',
            field=models.IntegerField(choices=[(4, 4), (2, 2)], null=True, verbose_name='How many ram slots'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='rgb',
            field=models.BooleanField(help_text="ONLY RGB LIGHT THAT'S PART OF THE MOBO"),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='theme',
            field=models.CharField(choices=[('dark', 'dark'), ('light', 'light')], max_length=6),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='wifi',
            field=models.BooleanField(help_text='Does it allow WIFI connectivity (without a cable)'),
        ),
        migrations.DeleteModel(
            name='computer',
        ),
    ]
