# Generated by Django 4.0.4 on 2022-10-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Computerizer/static/Blog/sales')),
                ('part', models.CharField(max_length=60)),
                ('body', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
    ]
