# Generated by Django 4.0.5 on 2022-12-07 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_post_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
    ]
