# Generated by Django 4.0.5 on 2022-11-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_rename_sales_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Computerizer/static/Blog/sales')),
                ('title', models.CharField(max_length=120)),
                ('posts', models.ManyToManyField(to='Blog.post')),
            ],
        ),
    ]
