# Generated by Django 4.0.5 on 2022-12-07 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_remove_post_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='file',
            new_name='body',
        ),
    ]
