# Generated by Django 4.0.5 on 2022-07-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oauth', '0002_customuser_password1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='password1',
            new_name='password_2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password2',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
