# Generated by Django 4.0.4 on 2022-11-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='Computerizer\\\\static\\\\Oauth\\\\media\\\\default.jpg', upload_to='Computerizer/static/Oauth/media'),
        ),
    ]
